#+title: Vyasa

#+BEGIN_QUOTE
Wherever there be anything you dost not comprehend, cease to continue writing

-- Vyasa, Adi Parva - Mahabharatam
#+END_QUOTE

*  What is the _*Vyasa Project*_?
=TODO=

* Getting Started Locally
** Basic setup instructions
*** Pre-requisites
1. Language Setup for Elixir. For any development environment of your choice, setup the necessary LSPs for elixir.
2. Docker
3. AWS cli
   We use minio for local setup. At least a dummy profile needs to be set up using the aws cli.

*** First Setup Steps
We first setup the servers that get run and then do teh data migration steps.

We can use the [[file:docs/migration_ritesh.livemd::Migration steps][livemarkdown here]] for the data migration steps.

1. start docker, use the [[file:docker-compose.yml][docker-compose file]] already available. This will start the minio, pg and the like
   #+begin_quote sh
   docker compose up
   #+end_quote
2. init aws cli, use a dummy profile
   writing to the =~/.aws/credentials= file will work as well:

   #+begin_quote toml
   [default]
   aws_access_key_id = secrettunnel
   aws_secret_access_key = secrettunnel
   #+end_quote
3. create the s3 bucket that shall be used
   #+begin_quote sh
   aws --endpoint-url http://localhost:9000 s3 mb s3://vyasa
   #+end_quote
4. install the elixir deps
   #+begin_quote elixir
   mix deps.get
   #+end_quote
5. do an initial db migration
   #+begin_quote elixir
   mix ecto.setup
   #+end_quote
6. [Data seeding] Seed the text, written and events
   This requires us to use a .json dump. [[./scripts/wow.json][Here's an example]] of such a dump.

   We also need some voices files to init the voices. The voices repo is a private repo for now, can be found [[https://github.com/ve1ld/voices][here]].

   For an easier time, use [[file:docs/migration_ritesh.livemd][this livemarkdown]].

*** Starting Steps
1. Start aux services by running docker compose up
2. Start the vyasa server
   #+begin_quote bash
iex --sname vyasa --cookie foofoo --dbg pry -S mix phx.server
   #+end_quote



* CLI Scripts Helpsheet
** 1. Running the shlokam.org scraper
#+begin_quote elixir
# build script
mix escript.build
# fetch from domain/path --storage :mode
./vyasa fetch shlokam.org/hanumanchalisa --storage file
#+end_quote

* Matter of Prior Work
We stand on the shoulders of giants. Here are some of the project that insipired this project into being started

** Prior Art
*** [[http://www.shivkumar.org/music/Thiruppavai-04-AazhiMazhaiKanna-Varali.htm][Shivkumar's Archives]]

Shivkumar Kalyanaraman has compiled and archived a wealth of song recordings, paired with word-by-word meanings

*** [[https://shaivam.org/hindu-prayer-hub/detail/521][Shaivam]]

Built and maintained by devotees since 1996 a wealth of textual archives

*** [[https://www.holy-bhagavad-gita.org/chapter/5/verse/8-9][Holy Bhagavad Gita]]

A tremendous effort by Jagadguru Kripaluji Trust

** Forms of Prior Art as Inspiration
*** [[http://worrydream.com/refs/Nelson-ComputerLibDreamMachines1975.pdf#page=57][Xanadu Pattern ]]

Ted Nelson the granddaddy of hypertext media, need I say more. The introduction to [[https://cs.brown.edu/people/nmeyrowi/LiteraryMachinesChapter2.pdf#page=12][Literary Machines]] is instructive to delineating the problem boundaries for literature

*** [[https://gwern.net/design][Design of Gwern.net]]

Gwern has incorporated sidenotes instead of footnotes on wide windows, drop caps, smallcaps, collapsible sections, automatic inflation-adjusted currency, Wikipedia-style link icons & infoboxes, custom syntax highlighting, extensive local archives to fight linkrot (archive engine), and an ecosystem of “popup”/“popin” annotations & previews of links for frictionless browsing—the net effect of hierarchical structures with collapsing and instant popup access to excerpts enables iceberg-like pages where most information is hidden but the reader can easily drill down as deep as they wish.

*** [[https://edwardtufte.github.io/tufte-css/][Tufte.css]]

Edward Tufte has developed a distinctive style in his works: simple, with well-set typography, extensive sidenotes, and elegant representations of graphs and charts

*** [[https://ctext.org/introduction][CText]]

Dr. Donald Sturgeon has compiled a great corpus of ancient (in particular pre-Qin and Han dynasty) Chinese texts in an organized and searchable format which has been composed through an parallel passage interface, word lists for semantic linking and ancient text database.

*** [[https://www.iwritewordsgood.com/apl/patterns/apl101.htm][Pattern Language]]
Christopher Alexander's pattern language arranges a series of  steps, in a certain way that allows the process of unfolding to proceed. The rules are ordered – sequenced – to unfold each part of the environment being created, smoothly and coherently [[https://www.livingneighborhoods.org/ht-0/morphogenesis-two.htm][enlarging the whole]].
